
# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check"

[jobs]

[jobs.check]
# command = ["cargo", "check", "--color", "always", "--features", "clients-1"]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-cortex-m4]
# command = ["cargo", "check", "--color", "always", "--features", "clients-1"]
command = ["cargo", "check", "--color", "always", "--target", "thumbv7em-none-eabi"]
need_stdout = false

[jobs.check-pc]
command = ["cargo", "check", "--color", "always", "--target", "x86_64-unknown-linux-gnu"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--tests", "--color", "always"]
need_stdout = false

[jobs.light]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
watch = ["src", "tests"]

[jobs.test-ext]
command = ["cargo", "test", "--color", "always", "--features", "virt,serde-extensions"]
need_stdout = true
watch = ["src", "tests"]

[jobs.doc]
command = ["cargo", "doc", "--color", "always"]
need_stdout = true

[jobs.doc-no-deps]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = true

