[package]
name = "trussed-derive"
version = "0.1.0"
description = "Derive macros for the trussed crate"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "2.0.53"

[dev-dependencies]
serde = { version = "1.0", default-features = false }
trussed = { version = "0.2", features = ["serde-extensions", "virt"] }
trussed-core = { version = "0.2", features = ["serde-extensions"] }
trussed-fs-info = "0.3"
trussed-manage = "0.3"
trussed-rsa-alloc = "0.5"
trussed-staging = { version = "0.5", features = ["fs-info", "manage"] }
